services:

  hermit:
    image: beavuck/hermit:latest
    pull_policy: always
    environment:
      HERMIT_SPECS_DIR: specs
    ports:
      - "8532:8532"
    volumes:
      - ./specs_assets:/specs:ro
