sonar.projectKey=beavuck-services_hermit
sonar.organization=beavuck-services
sonar.sources=src
sonar.exclusions=**/target/**, Cargo.lock, Cargo.toml
sonar.coverage.exclusions=src/main.rs
sonar.sourceEncoding=UTF-8
sonar.rust.lcov.reportPaths=lcov.info