sonar.projectKey=beavuck-services_hermit
sonar.organization=beavuck-services
sonar.sources=src
sonar.exclusions=**/target/**, Cargo.lock, Cargo.toml
sonar.coverage.inclusions=src/**/*.*
sonar.coverage.exclusions=
sonar.sourceEncoding=UTF-8
