info:
  name: get_tasks
  type: http
  seq: 1

http:
  method: GET
  url: "{{TASKFLOW_BASE_URL}}/projects/{{PROJECT_ID}}/tasks"
  auth: inherit

runtime:
  assertions:
    - expression: res.status
      operator: eq
      value: "200"
    - expression: res.body.total
      operator: isDefined
    - expression: res.body.page
      operator: isDefined
    - expression: res.body.limit
      operator: isDefined
    - expression: res.body.items
      operator: isArray
    - expression: res.body.items
      operator: isNotEmpty
    - expression: res.body.items[0].id
      operator: isDefined
    - expression: res.body.items[0].title
      operator: isDefined
    - expression: res.body.items[0].type
      operator: isDefined
    - expression: res.body.items[0].projectId
      operator: isDefined
    - expression: res.body.items[0].createdAt
      operator: isDefined
    - expression: res.body.items[0].updatedAt
      operator: isDefined

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
